//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXAM()
        {
            this.STUDENT_EXAM = new HashSet<STUDENT_EXAM>();
        }
    
        public int exam_id { get; set; }
        public int subject_id { get; set; }
        public string exam_name { get; set; }
        public int max { get; set; }
        public int pass { get; set; }
        public int weight { get; set; }
        public bool is_delete { get; set; }
    
        public virtual SUBJECT SUBJECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_EXAM> STUDENT_EXAM { get; set; }
    }
}
