//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDU.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLASS> CLASS { get; set; }
        public virtual DbSet<DAY> DAY { get; set; }
        public virtual DbSet<EXAM> EXAM { get; set; }
        public virtual DbSet<GENDER> GENDER { get; set; }
        public virtual DbSet<IN_OUT_BOX> IN_OUT_BOX { get; set; }
        public virtual DbSet<INTERACTIVE> INTERACTIVE { get; set; }
        public virtual DbSet<INTERACTIVE_TYPE> INTERACTIVE_TYPE { get; set; }
        public virtual DbSet<MESSAGE> MESSAGE { get; set; }
        public virtual DbSet<MESSAGE_MEDIA> MESSAGE_MEDIA { get; set; }
        public virtual DbSet<NEWS> NEWS { get; set; }
        public virtual DbSet<NEWS_MEDIA> NEWS_MEDIA { get; set; }
        public virtual DbSet<NOTIFICATION> NOTIFICATION { get; set; }
        public virtual DbSet<NOTIFICATION_TYPE> NOTIFICATION_TYPE { get; set; }
        public virtual DbSet<PERMISSION> PERMISSION { get; set; }
        public virtual DbSet<SECTION> SECTION { get; set; }
        public virtual DbSet<SESSION> SESSION { get; set; }
        public virtual DbSet<STUDENT_EXAM> STUDENT_EXAM { get; set; }
        public virtual DbSet<SUBJECT> SUBJECT { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TIME_SCHEDULE> TIME_SCHEDULE { get; set; }
        public virtual DbSet<USER> USER { get; set; }
        public virtual DbSet<USER_PERMISSION> USER_PERMISSION { get; set; }
        public virtual DbSet<USER_SUBJECT> USER_SUBJECT { get; set; }
        public virtual DbSet<USER_TYPE> USER_TYPE { get; set; }
    }
}
