//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWS_MEDIA
    {
        public int news_media_id { get; set; }
        public int news_id { get; set; }
        public string path { get; set; }
        public bool is_delete { get; set; }
    
        public virtual NEWS NEWS { get; set; }
    }
}
