//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTIFICATION
    {
        public int notification_id { get; set; }
        public int user_id { get; set; }
        public int notification_type_id { get; set; }
        public string title { get; set; }
        public string headline { get; set; }
        public System.DateTime date { get; set; }
        public int pk { get; set; }
        public bool is_delete { get; set; }
    
        public virtual NOTIFICATION_TYPE NOTIFICATION_TYPE { get; set; }
        public virtual USER USER { get; set; }
    }
}
