//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_EXAM
    {
        public int student_exam_id { get; set; }
        public int user_id { get; set; }
        public int exam_id { get; set; }
        public int mark { get; set; }
        public bool absent { get; set; }
        public System.DateTime date { get; set; }
        public bool is_delete { get; set; }
    
        public virtual EXAM EXAM { get; set; }
        public virtual USER USER { get; set; }
    }
}
