//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIME_SCHEDULE
    {
        public int time_schedule_id { get; set; }
        public int subject_id { get; set; }
        public int day_id { get; set; }
        public int session_id { get; set; }
        public int section_id { get; set; }
        public bool is_delete { get; set; }
    
        public virtual DAY DAY { get; set; }
        public virtual SECTION SECTION { get; set; }
        public virtual SESSION SESSION { get; set; }
        public virtual SUBJECT SUBJECT { get; set; }
    }
}
