//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.IN_OUT_BOX = new HashSet<IN_OUT_BOX>();
            this.IN_OUT_BOX1 = new HashSet<IN_OUT_BOX>();
            this.INTERACTIVE = new HashSet<INTERACTIVE>();
            this.NOTIFICATION = new HashSet<NOTIFICATION>();
            this.STUDENT_EXAM = new HashSet<STUDENT_EXAM>();
            this.USER_PERMISSION = new HashSet<USER_PERMISSION>();
            this.USER_SUBJECT = new HashSet<USER_SUBJECT>();
        }
    
        public int user_id { get; set; }
        public int user_type_id { get; set; }
        public Nullable<int> father_id { get; set; }
        public Nullable<int> mother_id { get; set; }
        public int gender_id { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public System.DateTime joining_date { get; set; }
        public string profile_image { get; set; }
        public bool is_delete { get; set; }
    
        public virtual GENDER GENDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IN_OUT_BOX> IN_OUT_BOX { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IN_OUT_BOX> IN_OUT_BOX1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INTERACTIVE> INTERACTIVE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTIFICATION> NOTIFICATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT_EXAM> STUDENT_EXAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_PERMISSION> USER_PERMISSION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_SUBJECT> USER_SUBJECT { get; set; }
        public virtual USER_TYPE USER_TYPE { get; set; }
    }
}
