//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_PERMISSION
    {
        public int user_permission_id { get; set; }
        public int user_id { get; set; }
        public int permission_id { get; set; }
        public bool is_delete { get; set; }
    
        public virtual PERMISSION PERMISSION { get; set; }
        public virtual USER USER { get; set; }
    }
}
